server:
  port: 5080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz963ju312wgv19502o.mysql.rds.aliyuncs.com:3306/chiyou-plus?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: mozi_root
    password: Cd40k1SKIXBQ
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.168.110:8848
  application:
    name: chiyou-plus-web-admin-service
